warning: "${LANGNET_TOOLS_HEADER}"
version: "0.5"

environment:
  - "GLOBAL_ENV_VAR=1"

log_location: ${LANGNET_TOOLS_DIR}/process-compose.log
log_level: debug

processes:
  diogenes:
    command: "bash --login -c 'just -f ${LANGNET_TOOLS_DIR}/justfile diogenes-server'"
    availability:
      restart: "always"
    environment:
      - "PHI_DIR=${LANGNET_TOOLS_DIR}/diogenes/Classics-Data/phi-latin"
      - "TLG_DIR=${LANGNET_TOOLS_DIR}/diogenes/Classics-Data/tlg_e"
    readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/"
        port: 8888

  langnet_cli:
    command: "just -f ${LANGNET_TOOLS_DIR}/justfile langnet-cli-server"
    availability:
      restart: "always"
    environment:
      - "LANGNET_LOG_LEVEL=INFO"
      - "LANGNET_CACHE_ENABLED=true"
    depends_on:
      diogenes:
        condition: process_healthy
    readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/api/health"
        port: 8000
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  zombie_reaper:
    command: "just -f ${LANGNET_TOOLS_DIR}/justfile langnet-dg-reaper"
    availability:
      restart: "always"
    depends_on:
      langnet_cli:
        condition: process_healthy

  sanskrit_heritage:
    command: "cd ${LANGNET_TOOLS_DIR}/sanskrit-heritage && devenv shell heritage-cgi"
    shutdown:
      command: "pkill httpd"
    availability:
      restart: "always"
    readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/"
        port: 48080
